---
- name: debian | Installing Pre-Reqs
  apt:
    name: "{{ item }}"
    state: "present"
  with_items: '{{ influxdb_debian_pre_reqs }}'

- name: debian | Adding InfluxDB Repo Key
  apt_key:
    url: "{{ influxdb_debian_repo_key }}"
    state: "present"

- name: debian | Adding InfluxDB Repo
  apt_repository:
    repo: "{{ influxdb_debian_repo }}"
    state: "present"

- name: debian | Installing InfluxDB
  apt:
    name: "influxdb"
    state: "present"
