---
- name: debian | Adding InfluxDB Repo Key
  apt_key:
    url: "{{ influxdb_debian_repo_key }}"
    state: present
  become: true
  register: result
  until: result is successful

- name: debian | Adding InfluxDB Repo
  apt_repository:
    repo: "{{ influxdb_debian_repo }}"
    state: present
  become: true
  register: result
  until: result is successful

- name: debian | Installing InfluxDB
  apt:
    name: "{{ 'influxdb=' + influxdb_version|string + '-1' }}"
    state: present
  become: true
  register: result
  until: result is successful
