---
# tasks file for ansible-influxdb

- include: debian.yml
  when: ansible_os_family == "Debian"

- include: redhat.yml
  when: ansible_os_family == "RedHat"

- include: config_db.yml
  when: config_influxdb_databases
